//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnchorMe.EntityFramework.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HarbourReservation
    {
        public int IDHarbourReservation { get; set; }
        public int UserID { get; set; }
        public int HarbourID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string AdditionalNotes { get; set; }
        public int ReservationStatusID { get; set; }
    
        public virtual Harbour Harbour { get; set; }
        public virtual UserData UserData { get; set; }
        public virtual ReservationStatus ReservationStatus { get; set; }
    }
}
