//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnchorMe.EntityFramework.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HarbourAdmin
    {
        public int IDHarbourAdmin { get; set; }
        public int LoginCredentialsID { get; set; }
        public int HarbourID { get; set; }
        public decimal Rating { get; set; }
    
        public virtual Harbour Harbour { get; set; }
        public virtual LoginCredentials LoginCredentials { get; set; }
    }
}
