//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnchorMe.EntityFramework.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginCredentials
    {
        public int IDLoginCredentials { get; set; }
        public int UserDataID { get; set; }
        public string Username { get; set; }
        public string Pwd { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
